site_name: FastDI
repo_url: https://github.com/OpenMindAmir/FastDI

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_signature_annotations: true

nav:
  - Home: index.md
  - API Reference:
      - Container: reference/container.md
      - Integrations: reference/integrations.md
      - Errors:  reference/errors.md
