site_name: FastIoC
site_url: https://OpenMindAmir.github.io/FastIoC
repo_url: https://github.com/OpenMindAmir/FastIoC

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  icon:
    repo: fontawesome/brands/github
  extra:
    footer: "hey"
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - versioning
  palette:
    - scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

plugins:
  - search
  - mike
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_signature_annotations: true

nav:
  - 💝DONATE💝: https://OpenMindAmir.ir/donate
  - Home: index.md
  - Guide:
    - Injectification: injectify.md
    - Dependency Registeration: register.md
    - Dependency Resolution: resolve.md
    - Passive Dependencies: passive.md
    - Dependency Lifetimes: lifetime.md
    - Nested Dependencies: nested.md
    - Dependency Overrides: override.md
    - Dispose (Singleton Clean-up): dispose.md
    - Passing Data to Dependencies: data.md
    - APIController: controller.md
    - Project Structure at Scale: scale.md
    - Integrated Mode: integrated.md
    - Hooks: hook.md
    - Logging System: log.md
  - API Reference:
      - Container: reference/container.md
      - Integrations: reference/integrations.md
      - Exceptions:  reference/exceptions.md
      - APIController: reference/controller.md

extra_css:
  - style.css


extra:
  homepage: https://OpenMindAmir.github.io/FastIoC
  social:
    - icon: fontawesome/solid/heart
      link: https://OpenMindAmir.ir/donate
    - icon: fontawesome/solid/globe
      link: https://OpenMindAmir.ir
    - icon: fontawesome/solid/envelope
      link: mailto:OpenMindAmir@gmail.com
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/OpenMindAmir
    - icon: fontawesome/brands/github
      link: https://github.com/OpenMindAmir
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OpenMindAmir

copyright: Amir R. Aliakbari &lt<a href="https://OpenMindAmir.ir" class="openmindamir">OpenMindAmir</a>&gt &copy 2025